"""empty message

Revision ID: 0735166546b0
Revises: c2cdaebc4e3e
Create Date: 2022-09-16 16:29:07.170406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0735166546b0'
down_revision = 'c2cdaebc4e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
